### ISSUE TITLE
Activate フラグが想定通りに動作していないと思われる点がある

### ISSUE THREAD

**Issue by junjanjon** [Z-me/NicoNicoStyle4MeetChromeExtension#10]
拡張機能の公開ありがとうございます！

フラグ名のタイポらしい点を見つけたためご連絡です。
`mns-active`  がフラグとして利用されていましたが、セットする場所が `nsm-active` でした。
https://github.com/junjanjon/NicoNicoStyle4MeetChromeExtension/commit/c2c2cec36135b90db0f0428f4e01bbde22b364c9

この変更をする前は、
一度 Activate した後も meet のメッセージスレッドを開いた後に拡張機能のアイコンをクリックしないと 文字列が流れてきませんでした。

この変更をすることで、
一度 Activate した後は meet のメッセージスレッドを開いた後に拡張機能のアイコンをクリックしなくても 文字列が流れてくるようになりました。

ご確認いただければうれしいです。

**Comment by Z-me** [comment]
ご連絡ありがとうございます。
完全にタイポですね。。
時間見つけて修正しておきます 🙇🏻

**Comment by Z-me** [comment]
https://github.com/Z-me/NicoNicoStyle4MeetChromeExtension/pull/9
こちらの対応で完了したためクローズ
